<style>
.commerce-connector--shops-list {
    list-style: none;
}
.commerce-connector--shops-list li a {
    float: left;
    margin-right: 10px;
}

</style>

<ul class="commerce-connector--shops-list">
<?php
foreach ($shoplist as $simpleProduct => $retails) { ?>
    <li id="retail-product-<?php echo $simpleProduct; ?>" class="<?php if (!in_array($simpleProduct, $currentEans)) { echo 'hidden'; } ?>">
    <?php foreach ($retails as $retail) { ?>
        <?php foreach ($retail['shoplist'] as $value) { ?>
            <a href="<?php echo $value['DEEPLINK']; ?>" target="_blank">
                <img src="<?php echo $value['shopdata']['LOGO']; ?>" alt="<?php echo $value['shopdata']['NAME']; ?>" title="<?php echo $value['shopdata']['NAME']; ?>"/>
            </a>
        <?php } ?>
    <?php } ?>
    </li>
<?php } ?>
</ul>
